// Fake YouTube live-chat content. Pools of viewers + comments by category.
// Chat.svelte picks lines based on the current game state.

export const VIEWERS = [
  // Ethan himself, talking back to the chat — appears often.
  { name: 'sendfood',        color: '#f5c842', vip: true, weight: 8 },
  // Regulars
  { name: 'cookielover',     color: '#c47ad9' },
  { name: 'kitchen_dad',     color: '#5db8e0' },
  { name: 'flavortown',      color: '#f08a3c' },
  { name: 'midnight_chef',   color: '#9b88ff' },
  { name: 'hungryghost',     color: '#94a0bd' },
  { name: 'PanQueen',        color: '#ff7eb1' },
  { name: 'umamiagain',      color: '#7adba0' },
  { name: 'sauce.boss',      color: '#ff9c5b' },
  { name: 'notachef',        color: '#a8b3ca' },
  { name: 'bigappetite',     color: '#ffd97a' },
  { name: 'breakfast_enj',   color: '#7ec5ff' },
  { name: 'recipebox',       color: '#52c07a' },
  { name: 'lurkingbtw',      color: '#7a85a0' },
  { name: 'first_comment',   color: '#e0a8ff' },
  { name: 'CulinaryCarl',    color: '#d4a824' },
  { name: 'PanFried',        color: '#ff8a8a' },
  { name: 'ChefDad42',       color: '#52c0c8' },
  // Friends of the channel
  { name: 'tacticizm',       color: '#5dd9c1', weight: 4 },
  { name: 'yourpizzahero',   color: '#ff6b6b', weight: 4 },
  { name: 'theboysquared',   color: '#9ac9ff', weight: 4 },
  { name: 'journeygames',    color: '#ffb56b', weight: 4 },
  { name: 'animeBJ',         color: '#ff7ed1', weight: 4 },
  { name: 'redhead',         color: '#ff5a3c', weight: 4 },
];

// Comments grouped by trigger context.
export const COMMENTS = {
  ambient: [
    'first',
    'gm ethan',
    'watching live',
    'finally home, time to chill',
    'comfort viewing',
    'anyone else binging the whole playlist',
    'just subscribed',
    'this stream is the best part of my day',
    'tell me you cook for a living without telling me',
    'lurking',
    'you got the best edits on this app',
    'whats the playlist song',
    'second day in a row checking in',
    'love the vibe',
    'always smooth',
    'long time viewer first time chatter',
    'how do you film this AND cook at the same time',
    'i cook with this on in the background lol',
    'where did you go to culinary school',
    'do you have a podcast',
    'background music slaps',
    'is the apron new',
    'whats the kitchen layout my place is so cramped',
    'how do you keep your knives so sharp',
    'do you do meal prep videos',
    'whos editing the videos',
    'do you actually eat all this after',
    'this is the algo doing its job',
    'tuning in from australia',
    'tuning in from norway',
    'first stream ive caught live!! hi',
    'sound check',
    'screen looks great',
    'this is so peaceful tbh',
    'youre the GOAT',
    'i learned so much from your channel',
    'ramsay who',
    'cant wait for the next vid',
    'binged the whole back catalog last night',
    'midnight snack inspo right here',
    'low key the most chill chat on yt',
    'mods are doing great today',
    'is this a vod or live',
    'just got off work let me catch up',
    'snack break with ethan',
    'baby is napping i finally have 20 min for this',
  ],
  cook: [
    'looks amazing 🤤',
    'im hungry now',
    'send some pls',
    'recipe drop when',
    'that plating tho',
    'i can smell it from here',
    'drooling fr',
    'okay chef',
    'this >>> restaurant',
    'this is making me eat my keyboard',
    'how did you get the color like that',
    'whats the secret',
    'oil temp looks perfect',
    'thats fire',
    'omg yes',
    'add salt now add salt now',
    'temperature control >>>',
    'thats a clean dice',
    'wrist game ridiculous',
    'flip it flip it FLIP IT',
    'i could never',
    'doing the lords work',
    'this is therapy',
    'patience pays off',
    'chefs kiss',
    'no notes',
    'instructions unclear i set my pan on fire',
  ],
  cook_eggs: [
    'eggs gang',
    'breakfast supremacy',
    'scrambled or bust',
    'add butter add butter add butter',
    'fluffy scramble unlocked',
    'how do you get them so creamy',
    'low heat low heat',
    'whisked or shaken',
    'salt at the end always',
    'eggs are an art form',
    'french or american style',
    'soft scrambled is god tier',
  ],
  cook_pasta: [
    'carbonara hype',
    'no cream right? respect',
    'i need pasta now',
    'pls drop the sauce recipe',
    'guanciale or pancetta',
    'fresh pepper >>>',
    'pasta water is the move',
    'al dente or im leaving',
    'never met a pasta i didnt love',
    'thats an italian grandma approved technique',
    'cant believe its not cream',
    'starchy water saves the day',
  ],
  cook_stirfry: [
    'wok hei moment',
    'that sizzle audio 👌',
    'beef stir fry slaps',
    'high heat hero',
    'velveting the beef??? next level',
    'wok flex',
    'tossing skills 10/10',
    'cornstarch slurry incoming',
    'ginger garlic combo never misses',
    'thats the breath of the wok',
  ],
  cook_sushi: [
    'sushi?? when did this happen',
    'knife skills 🔥',
    'rice game looking elite',
    'vinegar rice ratio is everything',
    'whats your fish source',
    'maki master',
    'who needs takeout',
    'is that a yanagiba',
    'sashimi cuts are clean',
    'where do you find fresh fish',
    'nori brand drop pls',
  ],
  cook_wellington: [
    'wellington in a youtube short?? icon',
    'no way this is one take',
    'three days of prep for 30s of footage',
    'duxelles done right',
    'thats a perfect medium rare',
    'pastry game STRONG',
    'mushroom dust >>>',
    'this is gordon ramsay coded',
    'whose birthday is this for',
    'i can hear that pastry crackle',
  ],
  cook_ramen: [
    'wagyu ramen i cannot',
    'the broth deserves its own channel',
    '$200 of ingredients let him cook',
    'noodle texture looks unreal',
    'tonkotsu or shoyu',
    'soft boiled egg pls dont overcook',
    'chashu looking divine',
    'this could be at a 3 michelin spot',
    'how long did that broth simmer',
    'a64 noodles whats the gauge',
  ],
  film_clip: [
    'lighting today is great',
    'mic quality is so clean',
    'whats your camera setup',
    'cinematic',
    'depth of field 👌',
    'shutter speed crispy',
    'who shoots this',
    'the framing is chef kiss',
    'b-roll is going to be SO good',
    'love the warm color grade',
    'tripod or gimbal',
    'shotgun mic or lav',
    'natural light gang',
    'love the macro shots',
    'overhead angle pls',
    'iso 800 lookin clean',
    'whatever lens this is i need it',
    'A7S? FX3?',
    'shot in 4k right',
    'shutter angle 180 i can tell',
  ],
  edit_video: [
    'edits are wild',
    'jump cuts crisp',
    'whoever cuts these deserves a raise',
    'the SFX 😭',
    'audio mix is too good',
    'transitions feel buttery',
    'pacing on point',
    'love the kinetic typography',
    'sound design is unmatched',
    'who scored this',
    'davinci or premiere',
    'subtitles are so well timed',
    'color grade is movie level',
    'three cameras minimum right',
    'the rhythm of the cuts is hypnotic',
  ],
  thumbnail: [
    'love the new thumbnail style',
    'CTR speedrun',
    'photoshop legend',
    'red arrow + open mouth = views',
    'thumbnail is selling me HARD',
    'youtube algorithm watching',
    'instant click',
    'whoever designs these is goated',
    'mr beast called',
  ],
  promote: [
    'shared with my whole feed',
    'told my friends',
    'algorithm cant ignore this',
    'manifesting 100k',
    'reposted on my story',
    'sent to the group chat',
    'told my mom',
    'pinning this',
    'screenshotting for later',
    'my fyp better serve me this twice',
    'mention this on the podcast',
    'add me to your priority list please ethan',
  ],
  collab: [
    'CROSSOVER EPISODE',
    'wait who is that',
    'two foodtubers one kitchen',
    'collab arc starting',
    'crossover of the year',
    'we are in our collab era',
    'tag em tag em',
    'when do you do binging with babish',
    'guest chef of the week!',
    'who invited the camera tho',
  ],
  sponsorship: [
    'is this an ad?',
    'sponsored but i forgive him',
    'they actually pay you??',
    'pls take the bag king',
    'brand deal hes officially big',
    'TAKE THE MONEY ethan',
    '#ad and im fine with it',
    'product placement king',
    'whats the discount code',
    'paid promo means hes winning',
    'this brand always shows up',
  ],
  merch: [
    'where do i buy the apron',
    'shipping to UK?',
    'merch dropped omg',
    'gimme that mug',
    'add me to the waitlist',
    'sizes please',
    'limited edition or restock?',
    'aprons sold out in 12 minutes lol',
    'price point??',
    'i want the hat',
    'restock alert pls',
  ],
  viral_video: [
    '🚀🚀🚀',
    'WE GOING VIRAL',
    'MY GUY',
    'i was here before it blew up',
    'tagging everyone i know',
    '🔥🔥🔥 the trending tab is coming',
    'this is THE one',
    'i KNEW IT',
    'twitter is about to lose it',
    'reddit front page incoming',
    'youtube trending pls',
    'i need to screenshot this',
    'we are SO back',
    'CALLED IT',
  ],
  buy_groceries: [
    'restock arc',
    'whats in the cart this week',
    'protein protein protein',
    'farmers market king',
    'sale at the asian grocer dont miss',
    'always shop hungry never',
    'whats the budget',
    'add eggs to the list',
    'olive oil running low?',
    'aldi sweep',
  ],
  // Big celebrations — used when a milestone fires
  milestone: [
    'HUGE 🎉',
    'congrats ethan',
    'we made it',
    'historic stream',
    '🥳🥳🥳',
    'this calls for cake',
    'CHAT WE DID IT',
    'pop the bottles',
    'level up moment',
    'screenshotting forever',
    'i will tell my grandkids about this stream',
    'the lore expands',
    'milestone unlocked!! pls do speech',
    'we ATE today',
    'GOAT confirmed',
  ],
  // The mayo running gag — fires occasionally from any random viewer.
  mayo: [
    'needs more mayo',
    'more mayo pls',
    'wheres the mayo',
    'add mayo',
    'mayo would fix it',
    'a little mayo wouldnt hurt',
    'controversial: mayo on that',
    'MAYO',
    'one more dollop of mayo and chef kiss',
    'this slaps but mayo would slap harder',
    'okay but where mayo',
    'genuinely begging for mayo here',
    'cant believe theres no mayo on this',
    'mayo on the side at least',
    'kewpie supremacy',
    'mayo nation rise up',
    'no shade but. mayo.',
    'a thin layer of mayo would not be a crime',
    'mayonnaise as a service',
    'add mayo or i unsub',
    'ethan listen. mayo.',
    'all i ask for is a small dish of mayo',
    'have you considered. mayo.',
  ],
  // @sendfood is Ethan — the creator chatting back to his own audience.
  sendfood: [
    'yall ready for this one',
    'thanks for hanging out',
    'real ones know',
    'shoutout the chat',
    'next video drops sunday',
    'wait til you see whats next',
    'kitchens cooking tonight',
    'this is the one',
    'appreciate every single one of you',
    'okay one more recipe and then im eating',
    'small batch tonight, big batch tomorrow',
    'follow for more',
    'we will get there',
    'no notes from me — clip it',
    'first time trying this on stream lol',
    'recipe in the description as always',
    'who needs seconds',
    'tell me what to make next',
    'gonna film one more clip then call it',
    'low key proud of this one',
    'thanks for the raid earlier',
    'mods love yall',
    'hydrate everyone',
    'taking suggestions in the comments',
    'merch link is pinned',
    'drink your water yall',
    'crazy that yall keep showing up like this',
    'see you sunday 8pm est',
    'wanna make one of these together? join discord',
    'we will hit the goal i promise',
    '@mods you running the giveaway after this?',
    'mom if youre watching hi',
    'this batch goes out to the regulars',
    'okay focus mode',
    'lemme cook',
    'gonna mute for a sec, brb',
    'who said something about mayo lol',
    'no i wont put mayo on the wellington stop asking',
    'fine ill think about the mayo',
  ],
};

// Recent-message tracker — avoid repeating the same line within the last N picks.
const recentSaid = [];
const RECENT_MAX = 12;
let chatIdCounter = 1;

export function pickViewer() {
  const total = VIEWERS.reduce((s, v) => s + (v.weight || 1), 0);
  let r = Math.random() * total;
  for (const v of VIEWERS) {
    r -= v.weight || 1;
    if (r <= 0) return v;
  }
  return VIEWERS[0];
}

export function pickComment(category) {
  const pool = COMMENTS[category] || COMMENTS.ambient;
  const fresh = pool.filter((c) => !recentSaid.includes(c));
  const source = fresh.length > 0 ? fresh : pool;
  const text = source[Math.floor(Math.random() * source.length)];
  recentSaid.push(text);
  while (recentSaid.length > RECENT_MAX) recentSaid.shift();
  return text;
}

export function makeMessage(category, viewer) {
  const v = viewer || pickViewer();
  let text;
  // ~6% chance any random viewer drops the mayo bit, regardless of context.
  if (Math.random() < 0.06) {
    text = pickComment('mayo');
  } else if (v.name === 'sendfood' && Math.random() < 0.85) {
    text = pickComment('sendfood');
  } else {
    text = pickComment(category);
  }
  return {
    id: chatIdCounter++,
    name: v.name,
    color: v.color,
    text,
    vip: !!v.vip,
  };
}
